### ISSUE TITLE
FFMpeg error causes youtube-dl to fail merging video and audio

### ISSUE THREAD

**Issue by nipponese** [homebrew-ffmpeg/homebrew-ffmpeg#72]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## Expected behavior

Tried running `youtube-dl` with only `-v` option. Usually this downloads the video and audio and merges them.

## Actual behavior

It fails when FFMpeg tries to merge video and audio:
```
ERROR: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError
```

## Command

The exact command you were trying to run:

```
youtube-dl -v https://youtu.be/XHPDMvjHNu4
```

The output that you got:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/XHPDMvjHNu4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Git HEAD: 8b677c0dd
[debug] Python version 3.9.2 (CPython) - macOS-11.2.3-arm64-arm-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] XHPDMvjHNu4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r4---sn-n4v7sn7z.googlevideo.com/videoplayback?expire=1615505328&ei=UFNKYLHcDMTikgaEyYz4DQ&ip=2601%3A645%3A8800%3Aa0%3Ac1fb%3A8c72%3A3d3d%3A5fde&id=o-AC-QOBhJdlwy5znH7b-LC4zyjab6L24MFI3KJD9ZLPZ4&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=qi&mm=31%2C29&mn=sn-n4v7sn7z%2Csn-n4v7knlk&ms=au%2Crdu&mv=m&mvi=4&pl=34&initcwndbps=1787500&vprv=1&mime=video%2Fmp4&ns=KrV1KaPXHg4GYtvIKrz_7dYF&gir=yes&clen=3908261&dur=23.490&lmt=1564615225707286&mt=1615483505&fvip=4&keepalive=yes&fexp=24001374%2C24007246&c=WEB&txp=5432432&n=Y1Pm1zlSqgtc2DKZW&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgBtfjztFffGSmDnWzTiPg8i2EByzYlVSFVNdlxKZ_rJsCIQD-tPXu1EzpsPqrF-S6BT9kchMme9nK9BDP9bn5Qi16bg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOPz9u-fxffkG2PynUABxkJhnFajm5r_pIUNc9097SzuAiEAi1EWqE5ep1nlTK0F_g_NFqmzQiR4Hura6Ct8Cn47t9c%3D'
[download] Destination: IMVU - The #1 Social Experience on Android-XHPDMvjHNu4.f136.mp4
[download] 100% of 3.73MiB in 00:00
[debug] Invoking downloader on 'https://r4---sn-n4v7sn7z.googlevideo.com/videoplayback?expire=1615505328&ei=UFNKYLHcDMTikgaEyYz4DQ&ip=2601%3A645%3A8800%3Aa0%3Ac1fb%3A8c72%3A3d3d%3A5fde&id=o-AC-QOBhJdlwy5znH7b-LC4zyjab6L24MFI3KJD9ZLPZ4&itag=140&source=youtube&requiressl=yes&mh=qi&mm=31%2C29&mn=sn-n4v7sn7z%2Csn-n4v7knlk&ms=au%2Crdu&mv=m&mvi=4&pl=34&initcwndbps=1787500&vprv=1&mime=audio%2Fmp4&ns=KrV1KaPXHg4GYtvIKrz_7dYF&gir=yes&clen=381788&dur=23.545&lmt=1564615046935532&mt=1615483505&fvip=4&keepalive=yes&fexp=24001374%2C24007246&c=WEB&txp=5431432&n=Y1Pm1zlSqgtc2DKZW&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMjtBedNjxgvLEoOA0GV_3RqaQB7csKIniKke1nSPix1AiB2bNfUVVD-lUoqdC1dwqeNj0rIB8XFkYt6IciLQKH0JA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOPz9u-fxffkG2PynUABxkJhnFajm5r_pIUNc9097SzuAiEAi1EWqE5ep1nlTK0F_g_NFqmzQiR4Hura6Ct8Cn47t9c%3D'
[download] Destination: IMVU - The #1 Social Experience on Android-XHPDMvjHNu4.f140.m4a
[download] 100% of 372.84KiB in 00:00
[ffmpeg] Merging formats into "IMVU - The #1 Social Experience on Android-XHPDMvjHNu4.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:IMVU - The #1 Social Experience on Android-XHPDMvjHNu4.f136.mp4' -i 'file:IMVU - The #1 Social Experience on Android-XHPDMvjHNu4.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:IMVU - The #1 Social Experience on Android-XHPDMvjHNu4.temp.mp4'
ERROR: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError
```

## Output of `brew config` and `brew doctor` commands

```
HOMEBREW_VERSION: 3.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b677c0ddd5f96b5521c1b353a9ca07dfe57b80e
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 364cc53cac316509ceb97f087c60796d3ddc5ab5
Core tap last commit: 35 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: N/A
Xcode: 12.4
Rosetta 2: false
Your system is ready to brew.
```

**Comment by slhck** [comment]
Thanks for adding all the info, but it does not seem to have anything to do with this repo. Issues here should be related to installing ffmpeg from this tap, not general ffmpeg errors or issues with other tools.

It might be worth posting this to the youtube-dl issue tracker.

**Comment by nipponese** [comment]
https://github.com/ytdl-org/youtube-dl/issues/28410
